# Generated by Django 4.2.7 on 2023-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='changed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
