# Generated by Django 4.2.7 on 2023-11-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0003_artist_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.DateTimeField()),
                ('author', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=32)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_1_app.director')),
            ],
        ),
    ]
