# Generated by Django 4.2.7 on 2023-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0004_director_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='year',
            field=models.IntegerField(),
        ),
    ]
