# Generated by Django 4.2.7 on 2024-01-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0007_chat_comment_country_message_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
