# Generated by Django 4.2.7 on 2024-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0012_postedit_subscribe_likepost_likecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(to='django_1_app.message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(to='django_1_app.likecomment'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='django_1_app.likepost'),
        ),
    ]
