# Generated by Django 4.2.7 on 2024-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0013_remove_comment_post_remove_likecomment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='django_1_app.comment'),
        ),
    ]
